### GET request to example server
GET http://localhost:3000

### All Users
GET localhost:3000/users

### User by ID
GET localhost:3000/users/qvpLe0X8D9XiYISI4g7P

### CREATE USER
POST localhost:3000/users
Content-Type: application/json

{
  "name": "sdadada",
  "email": "fffff@gabs.com",
  "password": "12345678"
}

### Change User
PUT localhost:3000/users/qvpLe0X8D9XiYISI4g7P
Content-Type: application/json

{
  "name": "MARIANA LOPES",
  "email": "Emaildamari@allala.com"
}

### DELETE USER
DELETE localhost:3000/users/r5l0DUTNw5HGVeEL2OuD

### DELETE ALL
DELETE localhost:3000/users/0123456789
###