### GET request to example server
GET http://localhost:3000

### All Users
GET localhost:3000/users

### User by ID
GET localhost:3000/users/1DFCDUakIKUSCQi9eSJN

### CREATE USER
POST localhost:3000/users
Content-Type: application/json

{
  "name": "sdadada",
  "email": "lalalalla@lalalal.com"
}

### Change User
PUT localhost:3000/users/xkywFxuLk1wkT4UyiQTl
Content-Type: application/json

{
  "name": "MARIANA LOPES",
  "email": "Emaildamari@allala.com"
}

### DELETE USER
DELETE localhost:3000/users/1DFCDUakIKUSCQi9eSJN

### DELETE ALL
DELETE localhost:3000/users/0123456789
###