### GET request to example server
GET http://localhost:3000

###Get Users
GET localhost:3000/users

###GEt user by id
GET localhost:3000/users/1

### POST CREATE USER
POST localhost:3000/users
Content-Type: application/json

{
  "name": "MAriana",
  "email": "lalalalla@lalalal.com"
}

### PUT Change ,User
PUT localhost:3000/users/2
Content-Type: application/json

{
  "name": "MARIANA LOPES",
  "email": "Emaildamari@allala.com"
}

###
DELETE localhost:3000/users/1

###